// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/distuurbia/tradingService/internal/model"

	uuid "github.com/google/uuid"
)

// TradingServiceService is an autogenerated mock type for the TradingServiceService type
type TradingServiceService struct {
	mock.Mock
}

// AddPosition provides a mock function with given fields: ctx, position
func (_m *TradingServiceService) AddPosition(ctx context.Context, position *model.Position) error {
	ret := _m.Called(ctx, position)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Position) error); ok {
		r0 = rf(ctx, position)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClosePosition provides a mock function with given fields: ctx, profileID, positionID
func (_m *TradingServiceService) ClosePosition(ctx context.Context, profileID uuid.UUID, positionID uuid.UUID) (float64, error) {
	ret := _m.Called(ctx, profileID, positionID)

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (float64, error)); ok {
		return rf(ctx, profileID, positionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) float64); ok {
		r0 = rf(ctx, profileID, positionID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, profileID, positionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAllOpenedPositionsByProfileID provides a mock function with given fields: ctx, profileID
func (_m *TradingServiceService) ReadAllOpenedPositionsByProfileID(ctx context.Context, profileID uuid.UUID) ([]*model.OpenedPosition, error) {
	ret := _m.Called(ctx, profileID)

	var r0 []*model.OpenedPosition
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.OpenedPosition, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.OpenedPosition); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OpenedPosition)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTradingServiceService creates a new instance of TradingServiceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTradingServiceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TradingServiceService {
	mock := &TradingServiceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
