// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: trading.proto

package trading

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradingServiceServiceClient is the client API for TradingServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradingServiceServiceClient interface {
	AddPosition(ctx context.Context, in *AddPositionRequest, opts ...grpc.CallOption) (*AddPositionResponse, error)
	ClosePosition(ctx context.Context, in *ClosePositionRequest, opts ...grpc.CallOption) (*ClosePositionResponse, error)
	ReadAllOpenedPositionsByProfileID(ctx context.Context, in *ReadAllOpenedPositionsByProfileIDRequest, opts ...grpc.CallOption) (*ReadAllOpenedPositionsByProfileIDResponse, error)
}

type tradingServiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradingServiceServiceClient(cc grpc.ClientConnInterface) TradingServiceServiceClient {
	return &tradingServiceServiceClient{cc}
}

func (c *tradingServiceServiceClient) AddPosition(ctx context.Context, in *AddPositionRequest, opts ...grpc.CallOption) (*AddPositionResponse, error) {
	out := new(AddPositionResponse)
	err := c.cc.Invoke(ctx, "/TradingServiceService/AddPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceServiceClient) ClosePosition(ctx context.Context, in *ClosePositionRequest, opts ...grpc.CallOption) (*ClosePositionResponse, error) {
	out := new(ClosePositionResponse)
	err := c.cc.Invoke(ctx, "/TradingServiceService/ClosePosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceServiceClient) ReadAllOpenedPositionsByProfileID(ctx context.Context, in *ReadAllOpenedPositionsByProfileIDRequest, opts ...grpc.CallOption) (*ReadAllOpenedPositionsByProfileIDResponse, error) {
	out := new(ReadAllOpenedPositionsByProfileIDResponse)
	err := c.cc.Invoke(ctx, "/TradingServiceService/ReadAllOpenedPositionsByProfileID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradingServiceServiceServer is the server API for TradingServiceService service.
// All implementations must embed UnimplementedTradingServiceServiceServer
// for forward compatibility
type TradingServiceServiceServer interface {
	AddPosition(context.Context, *AddPositionRequest) (*AddPositionResponse, error)
	ClosePosition(context.Context, *ClosePositionRequest) (*ClosePositionResponse, error)
	ReadAllOpenedPositionsByProfileID(context.Context, *ReadAllOpenedPositionsByProfileIDRequest) (*ReadAllOpenedPositionsByProfileIDResponse, error)
	mustEmbedUnimplementedTradingServiceServiceServer()
}

// UnimplementedTradingServiceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTradingServiceServiceServer struct {
}

func (UnimplementedTradingServiceServiceServer) AddPosition(context.Context, *AddPositionRequest) (*AddPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPosition not implemented")
}
func (UnimplementedTradingServiceServiceServer) ClosePosition(context.Context, *ClosePositionRequest) (*ClosePositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosePosition not implemented")
}
func (UnimplementedTradingServiceServiceServer) ReadAllOpenedPositionsByProfileID(context.Context, *ReadAllOpenedPositionsByProfileIDRequest) (*ReadAllOpenedPositionsByProfileIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAllOpenedPositionsByProfileID not implemented")
}
func (UnimplementedTradingServiceServiceServer) mustEmbedUnimplementedTradingServiceServiceServer() {}

// UnsafeTradingServiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradingServiceServiceServer will
// result in compilation errors.
type UnsafeTradingServiceServiceServer interface {
	mustEmbedUnimplementedTradingServiceServiceServer()
}

func RegisterTradingServiceServiceServer(s grpc.ServiceRegistrar, srv TradingServiceServiceServer) {
	s.RegisterService(&TradingServiceService_ServiceDesc, srv)
}

func _TradingServiceService_AddPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServiceServer).AddPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TradingServiceService/AddPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServiceServer).AddPosition(ctx, req.(*AddPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingServiceService_ClosePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServiceServer).ClosePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TradingServiceService/ClosePosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServiceServer).ClosePosition(ctx, req.(*ClosePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingServiceService_ReadAllOpenedPositionsByProfileID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllOpenedPositionsByProfileIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServiceServer).ReadAllOpenedPositionsByProfileID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TradingServiceService/ReadAllOpenedPositionsByProfileID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServiceServer).ReadAllOpenedPositionsByProfileID(ctx, req.(*ReadAllOpenedPositionsByProfileIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradingServiceService_ServiceDesc is the grpc.ServiceDesc for TradingServiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradingServiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TradingServiceService",
	HandlerType: (*TradingServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPosition",
			Handler:    _TradingServiceService_AddPosition_Handler,
		},
		{
			MethodName: "ClosePosition",
			Handler:    _TradingServiceService_ClosePosition_Handler,
		},
		{
			MethodName: "ReadAllOpenedPositionsByProfileID",
			Handler:    _TradingServiceService_ReadAllOpenedPositionsByProfileID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trading.proto",
}
